### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by mwkroening**
This will fix one third of your current problems with Travis-CI

### CODE REVIEW

**Comment by mwkroening** [comment]
To fix the rest of the problems it is worth looking at
https://docs.travis-ci.com/user/encryption-keys/

**Comment by mwkroening** [comment]
Okay then ^^

**Comment by mwkroening** [comment]
Are there any reasons to build with OracleJDK?
I think best practice is to build with openjdk-ea to ensure future proof compatibility with the RI-JDK and any legacy versions one would like to support.
If acceptable I would suggest removing any OracleJDKs.

**Comment by mwkroening** [comment]
The failures on Java versions greater than 8 are caused by the cobertura-maven-plugin:
https://github.com/mojohaus/cobertura-maven-plugin/issues/30

**Comment by DataSecs** [comment]
The main problem with cobertura I have is the non-existing support of lambda expression parsing, which causes to crash the parser of cobertura. Therefore I think it's a good suggestion to switch to JaCoCo. I've read about it previously and agree that it would be worth trying it out. Very kind of you to do some research and provide information about the things you suggest!! :)
The was no specific reason to build with the OracleJDK, it was just the first thing I tried to be honest. But as you already said it's definitely necessary to build with the openjdk-ea. I see no reason in not trying to build with the OracleJDKs, as they could be marked as "failures allowed" which would prevent any complications.

**Pull request merged**
